Add static-d3js example
Cycling74/n4m-examples pull request #7
Opened 2018-10-17 10:24 UTC by julianrubisch

I've got another one for you, enjoy!

2018-10-18 21:12 UTC, catarak requested changes

2018-10-18 21:12 UTC, catarak commented on static-d3js/README.md
> +4. Send a `[d3]` message followed by a valid d3js script file. An example based on Mike Bostock's [grouped bar chart](https://bl.ocks.org/mbostock/3887051) is provided.
can you add another step here that you have to enable the toggle in order to render the png in Max? 

it would also be rad if these steps were enumerated in the Max patch-some comment bubbles with numbers.

2018-10-18 21:12 UTC, catarak commented
@starakaj / @fde31 could you take a look at this as well?

2018-10-19 09:25 UTC, julianrubisch commented on static-d3js/README.md
> +4. Send a `[d3]` message followed by a valid d3js script file. An example based on Mike Bostock's [grouped bar chart](https://bl.ocks.org/mbostock/3887051) is provided.
sure, hang on!

2018-10-26 20:34 UTC, starakaj commented on static-d3js/data/data.csv
> +PA,737462,1345341,679201,1203944,3157759,3414001,1910571
add end of file newline

2018-10-26 20:35 UTC, starakaj commented on static-d3js/data/groupchart.js
> +const csvString = fs.readFileSync('./data/data.csv', 'UTF-8').toString();
Use quotes instead of single quotes

2018-10-26 20:35 UTC, starakaj commented on static-d3js/data/groupchart.js
> +    var g = svg.append("g").attr("transform", "translate(" + options.margin.left + "," + options.margin.top + ")");
Use let instead of var

2018-10-26 20:36 UTC, starakaj commented on static-d3js/data/groupchart.js
> +}
Fix indentation (mix of tabs and spaces)

2018-10-26 20:41 UTC, starakaj commented on static-d3js/data/style.css
> +}
Add end of file newline.

2018-10-26 20:41 UTC, starakaj commented on static-d3js/data/groupchart.js
> +}
Add end of file newline.

2018-10-26 20:41 UTC, starakaj commented on static-d3js/static-d3.js
> +const svg2png = require('svg2png');
Use double quotes

2018-10-26 20:42 UTC, starakaj commented on static-d3js/static-d3.js
> +	var d3n = new D3Node(options);
let not var

2018-10-26 20:42 UTC, starakaj commented on static-d3js/static-d3.js
> +});
end of file newline

2018-10-26 20:42 UTC, starakaj commented on static-d3js/static-d3.js
> +});
Fix indentation (mix of tabs and spaces)

2018-10-26 20:52 UTC, starakaj requested changes
First of all, sorry it took so long to get this pull request looked at! It caused some discussion and forced some decisions on our part, which is good, but which took some time.

Anyway, now that I have the chance to look more closely, this looks great, thanks for submitting. I'm just going to ask you to make some small stylistic changes, fixing a few linting errors. If you look in the repository root, you'll find a file called `.eslintrc.js`, which defines the linting rules for this repo, for use with ESLint. We should have automation set up to request changes to a PR automatically if it fails these rules, but for now I'm going to make the request myself.

Also, we didn't mention it in the "How to submit an example", but pull requests should be made from a uniquely named feature branch that has been rebased onto master, rather than your forked master branch. Otherwise, your new PR includes commits from the other PR. This will all be documented soon, thanks for bearing with us.

And most of all, thanks again for submitting this PR!

2018-10-27 05:15 UTC, julianrubisch commented
> If you look in the repository root, you'll find a file called .eslintrc.js, which defines the linting rules for this repo, for use with ESLint

Right now I‘m wondering why my editor didn’t pick that up... hmmm...

> Also, we didn't mention it in the "How to submit an example", but pull requests should be made from a uniquely named feature branch

I was already wondering …

> We should have automation set up to request changes to a PR automatically if it fails these rules

Reach out if you need help with the CI!

2018-11-09 10:51 UTC, julianrubisch commented
Is there something else I can do to advance this?

2018-11-09 16:51 UTC, catarak commented
sorry about the slowness on our end, @julianrubisch! internally, we've been having some discussions about how to organize c74 content/examples and user submitted examples and are going to change things up. still very interested in showcasing community work!

however, because we haven't switched things over yet, i'm going to ask you to fix some linting errors. you can see the errors [here, on Travis](https://travis-ci.com/Cycling74/n4m-examples/builds/90837151), or by running `npm run lint` in the root of the n4m-examples repository. you may be able to fix some of the errors automatically by running `npm run lint-fix`. let me know if you need any help with that!

2018-11-09 16:51 UTC, catarak approved these changes

2018-11-09 17:04 UTC, julianrubisch commented
Sure, I just have to sync it with the upstream repo!

2018-11-10 13:10 UTC, starakaj approved these changes

2018-11-10 13:11 UTC, starakaj commented
Outstanding. Thanks so much for your patience as we work things out on our end, very happy to get this merged.

2018-11-10 13:11 UTC, merged